{% set name = "ANTs" %}
{% set version = "2.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ANTsX/ANTs/archive/v{{ version }}.tar.gz
  sha256: b38bc5438a7bef0c460dc7014320fee58dd1439e2397876645ad9269f52d9451

build:
  number: 2
  script:
    - mkdir build
    - cd build
    # For Unix (not win)
    - cmake -G Ninja ${CMAKE_ARGS} -DANTS_SUPERBUILD:BOOL=OFF -DBUILD_SHARED_LIBS:BOOL=ON -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_INSTALL_LIBDIR:STRING=lib -DCMAKE_INSTALL_PREFIX:STRING=${PREFIX} -DCMAKE_PREFIX_PATH:STRING=${PREFIX} -DRUN_SHORT_TESTS:BOOL=ON -DRUN_LONG_TESTS:BOOL=OFF -DUSE_SYSTEM_ITK:BOOL=ON ${SRC_DIR}  # [not win]
    - cmake --build . --parallel ${CPU_COUNT} --target install  # [not win]
    - if [[ "${CONDA_BUILD_CROSS_COMPILATION:-}" != "1" || "${CROSSCOMPILING_EMULATOR}" != "" ]]; then ctest --parallel ${CPU_COUNT} --extra-verbose --output-on-failure; fi  # [not win]
    # For Windows (win)
    - set "CMAKE_ARGS=%CMAKE_ARGS% -DCMAKE_INSTALL_LIBDIR:STRING=%LIBRARY_LIB% -DCMAKE_INSTALL_PREFIX:STRING=%LIBRARY_PREFIX% -DCMAKE_PREFIX_PATH:STRING=%LIBRARY_PREFIX% -DBUILD_SHARED_LIBS:BOOL=ON -DANTS_SUPERBUILD:BOOL=OFF -DUSE_SYSTEM_ITK:BOOL=ON -DCMAKE_BUILD_TYPE:STRING=Release"  # [win]
    - cmake %CMAKE_ARGS% %SRC_DIR%  # [win]
    - cmake --build . --config Release --parallel %CPU_COUNT% --target install  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake >=3.16.3
    - ninja
  host:
    - libboost-headers
    - libitk-devel
  run:
    - {{ pin_compatible('libitk', min_pin='x.x', max_pin='x.x') }}

test:
  commands:
    - antsRegistration --help

about:
  home: https://stnava.github.io/ANTs/
  license: Apache-2.0
  license_file: COPYING.txt
  summary: >
    ANTs computes high-dimensional mappings to capture the statistics of brain structure and function
  doc_url: http://stnava.github.io/ANTsDoc
  dev_url: https://github.com/ANTsX/ANTs/wiki

extra:
  recipe-maintainers:
    - ghisvail
