# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

jobs:
- job: win
  pool:
    vmImage: windows-2022
  strategy:
    matrix:
      win_64_:
        CONFIG: win_64_
        UPLOAD_PACKAGES: 'True'
  timeoutInMinutes: 360
  variables:
    CONDA_BLD_PATH: D:\\bld\\
    MINIFORGE_HOME: D:\Miniforge
    UPLOAD_TEMP: D:\\tmp
    SET_PAGEFILE: 'True'

  steps:

    - script: |
        call ".scripts\run_win_build.bat"
        set "CMAKE_ARGS=%CMAKE_ARGS% -DCMAKE_INSTALL_LIBDIR:STRING=%LIBRARY_LIB% -DCMAKE_INSTALL_PREFIX:STRING=%LIBRARY_PREFIX% -DCMAKE_PREFIX_PATH:STRING=%LIBRARY_PREFIX% -DBUILD_SHARED_LIBS:BOOL=ON -DANTS_SUPERBUILD:BOOL=OFF -DUSE_SYSTEM_ITK:BOOL=ON -DCMAKE_BUILD_TYPE:STRING=Release"
      displayName: Run Windows build
      env:
        MINIFORGE_HOME: $(MINIFORGE_HOME)
        CONDA_BLD_PATH: $(CONDA_BLD_PATH)
        PYTHONUNBUFFERED: 1
        CONFIG: $(CONFIG)
        CI: azure
        flow_run_id: azure_$(Build.BuildNumber).$(System.JobAttempt)
        remote_url: $(Build.Repository.Uri)
        sha: $(Build.SourceVersion)
        UPLOAD_PACKAGES: $(UPLOAD_PACKAGES)
        UPLOAD_TEMP: $(UPLOAD_TEMP)
        BINSTAR_TOKEN: $(BINSTAR_TOKEN)
        FEEDSTOCK_TOKEN: $(FEEDSTOCK_TOKEN)
        STAGING_BINSTAR_TOKEN: $(STAGING_BINSTAR_TOKEN)
